---
was_nodeagent_sync__was_install_location: "{{ was_install_location  | default('/usr/WebSphere9/AppServer') }}"
# was_nodeagent_sync__node_profile_name: "{{ inventory_hostname_short }}"
# was_nodeagent_sync__dmgr_profile_name: "{{ inventory_hostname_short }}Dmgr"
was_nodeagent_sync__node_profile_name: "{{ nodeagent_profile_name | default(inventory_hostname_short) }}"
was_nodeagent_sync__dmgr_profile_name: "{{ dmgr_profile_name | default(inventory_hostname_short ~ 'Dmgr') }}"
was_nodeagent_port: 9879
