---
was_dmgr_status__was_install_location: "{{ was_install_location  | default('/usr/WebSphere9/AppServer') }}"
  #was_dmgr_status__node_profile_name: "{{ inventory_hostname_short }}Dmgr"
was_dmgr_status__node_profile_name: "{{ dmgr_profile_name | default(inventory_hostname_short ~ 'Dmgr') }}"
