---
- name: "Assigning roles to users"
  hosts: all
  become: true
  become_user: usb-cg3-qa-wasadmin
  tasks:
    - name: Run updation part
      ansible.builtin.include_role:
        name: was-userrole-assigning
      register: user_role_reg
      ignore_errors: true

    - name: Log other_role_or_task result
      ansible.builtin.lineinfile:
        path: "{{ log_status_file_dir }}"
        line: "Users_role assigning Status: {{ 'Completed' if user_role_reg is succeeded else 'Failed' }}"
