---
- name: "Configure virtual hosts"
  hosts: all
  become: true
  become_user: usb-cg3-qa-wasadmin

  tasks:
    - name: Run updation part
      ansible.builtin.include_role:
        name: was-create-virtual-host-port-config
      register: app_server_result
      ignore_errors: true

    - name: Log other_role_or_task result
      ansible.builtin.lineinfile:
        path: "{{ log_status_file_dir }}"
        line: "Was virtual Host and ports updation Status: {{ 'Completed' if app_server_result is succeeded else 'Failed' }}"
