---
- name: "Create users"
  hosts: all
  become: true
  become_user: usb-cg3-qa-wasadmin
  tasks:
    - name: Run soap properties updation part
      ansible.builtin.include_role:
        name: was-createusers
      register: was_users_creation_result
      ignore_errors: true

    - name: Log other_role_or_task result
      ansible.builtin.lineinfile:
        path: "{{ log_status_file_dir }}"
        line: "was users creation result Status: {{ 'Completed' if was_users_creation_result is succeeded else 'Failed' }}"
