---
- name: "Configure Soap client prop updation and encrypt"
  hosts: all
  become: true
  become_user: usb-cg3-qa-wasadmin
  vars:
    log_status_file_dir: "/home/{{ was_username }}/logfile.txt"
    tasks_to_update:
      - "Configure SOAP client properties"
  tasks:
    - name: Ensure log file exists
      ansible.builtin.file:
        path: "{{ log_status_file_dir }}"
        state: touch
        mode: '0755'

    - name: Run soap properties updation part
      ansible.builtin.include_role:
        name: soap_properties_updation_encryption
      register: soap_prop_update_result
      ignore_errors: true

    - name: Log other_role_or_task result
      ansible.builtin.lineinfile:
        path: "{{ log_status_file_dir }}"
        line: "Soap client properties updation: {{ 'Completed' if soap_prop_update_result is succeeded else 'Failed' }}"
