---
- name: Perform WAS Deployment manager status task
  hosts: all
  become: true
  become_user: "usb-cg3-qa-wasadmin"
  vars_files:
    - vars/main.yml
  tasks:
    - name: Status of dmgr
      ansible.builtin.include_role:
        name: was_dmgr_status
      # when: dmgr_status == "dmgr_status"
