---
- name: "Configure business banner msg in WAS"
  hosts: all
  become: true
  become_user: usb-cg3-qa-wasadmin
  vars_files:
    - vars/main.yml
  tasks:
    - name: Ensure log file exists
      ansible.builtin.file:
        path: "{{ log_status_file_dir }}"
        state: touch
        mode: '0755'

    - name: Run soap properties updation part
      ansible.builtin.include_role:
        name: was_business_banner_msg
      register: banner_msg_result
      ignore_errors: true

    - name: Log other_role_or_task result
      ansible.builtin.lineinfile:
        path: "{{ log_status_file_dir }}"
        line: "Banner msg Status: {{ 'Completed' if banner_msg_result is succeeded else 'Failed' }}"
