---
# was_base_path: "/usr/WebSphere9/AppServer"
# was_username: "usb-cg3-qa-wasadmin"
# was_password: "Welcome2ibm"
# bin_directory: "{{ was_base_path }}/profiles/{{ profile_name }}/bin"
# response_file: "{{ bin_directory }}/was_config_dmgr_jvm.py"
# template_file: "was_config_dmgr_jvm.py.j2"
# success_file: "{{ bin_directory }}/was-dmgr-config-jvm.success"
# was_owner: "usb-cg3-qa-wasadmin"
# was_group: "usb-was-grp"
# log_dir: "/vpapp/logs/{{ bank_id }}/CG3-AccesspointeII"
# log_grp: "wasloggp"
# log_files:
  # - was_config_custom_properties.j2
  # - was_config_depth.j2
  # - was_config_trace_logs.j2
  # - was_config_umask.j2
  # - was_config_webcontainer_transport_chains_enabling.j2
  # - was_config_dmgr_jvm.j2
  # - was_config_ibm_service_logs.j2
  # - was_config_jvm_logs.j2
  # - was_config_process_logs.j2
  # - was_config_sso.j2
  # - was-config_shared_library.j2
# sts_file: setSTS-for-DMGR.j2
# scripts_dir: "/home/{{ was_username }}/Scripts"
