---
- name: "Verifiy if Profile already exists"
  ansible.builtin.stat:
    path: "{{ was_base_path }}/profiles/{{ dmgr_profile_name }}"
  register: profile_already_exists

- name: Verify if pid file
  ansible.builtin.shell: ps -p `cat "{{ was_base_path }}/profiles/{{ dmgr_profile_name }}/logs/dmgr/dmgr.pid"`
  register: "dmgr_is_running"
  ignore_errors: true
  failed_when: false
  changed_when: dmgr_is_running.rc != 0

- name: "Verifiy if Deployment Manager is already created"
  ansible.builtin.stat:
    path: "{{ dmgr_response_file }}"
  register: dmgr_already_created

- name: "Generate Response file for deployment manager"
  ansible.builtin.template:
    src: "{{ dmgr_template_file }}"
    dest: "{{ dmgr_response_file }}"
    owner: "{{ was_owner }}"
    group: "{{ was_group }}"
    mode: '0755'
  when: not dmgr_already_created.stat.exists

- name: "Create profile for deployment manager"
  ansible.builtin.command: >
    {{ was_base_path }}/bin/manageprofiles.sh -response {{ dmgr_response_file }}
  register: create_dmgr_profile_output_reg
  args:
    chdir: "{{ bin_directory }}"
  when: not dmgr_already_created.stat.exists
  changed_when: ( create_dmgr_profile_output_reg.stdout.find('INSTCONFSUCCESS') != -1)
  failed_when: ( create_dmgr_profile_output_reg.stdout.find('INSTCONFFAILED') != -1)

- name: Print the result of deployment manager
  ansible.builtin.debug:
    msg: "{{ create_dmgr_profile_output_reg }}"
  when: not dmgr_already_created.stat.exists

- name: "Verifiy if Profile is already created"
  ansible.builtin.stat:
    path: "{{ was_base_path }}/profiles/{{ profile_name }}/logs/AboutThisProfile.txt"
  register: profile_log_aboutprofile

- name: Display the Profile Details
  ansible.builtin.command: "cat {{ was_base_path }}/profiles/{{ profile_name }}/logs/AboutThisProfile.txt"
  register: profile_output
  changed_when: profile_log_aboutprofile.stat.exists

- name: Print the Profile Details
  ansible.builtin.debug:
    msg: "{{ profile_output }}"
  when: profile_output.rc == 0

- name: Status of Servers
  ansible.builtin.command: "sh {{ was_base_path }}/profiles/{{ profile_name }}/bin/startServer.sh -all -username {{ was_username }} -password {{ was_password }}"
  register: status_server
  changed_when: status_server.rc == 0
  failed_when: status_server.rc != 0

- name: Print the result of start deployment manager
  ansible.builtin.debug:
    msg: "{{ status_server }}"
  when: status_server.rc == 0

# - name: Start DMGR Profile
  # ansible.builtin.command: "sh {{ was_base_path }}/profiles/{{ profile_name }}/bin/startManager.sh -username {{ was_username }} -password {{ was_password }}"
  # register: dmgr_start
  # changed_when: dmgr_start.rc == 0
  # failed_when: dmgr_start.rc != 0

# - name: Print the result of start deployment manager
  # ansible.builtin.debug:
    # msg: "{{ dmgr_start }}"
  # when: dmgr_start.rc == 0

# - name: Add port 9043/tcp to the public zone permanently
  # ansible.posix.firewalld:
    # port: 9043/tcp
    # zone: public
    # permanent: yes
    # state: enabled
  # when: dmgr_start.rc == 0

# - name: Reload firewall to apply changes
  # ansible.posix.firewalld:
    # immediate: yes
    # state: reloaded
  # when: dmgr_start.rc == 0

- name: "Purge Response file"
  ansible.builtin.file:
    path: "{{ dmgr_response_file }}"
    state: absent
