---

# - name: Loop through JSON data and print values
#   debug:
#     msg: "Username: {{ item.username }}, Password: {{ item.password }}, Email: {{ item.email }}"
#   loop: "{{ users_list_json }}"

# - meta: end_play

- name: "Verifiy if Profile already exists"
  ansible.builtin.stat:
    path: "{{ was_base_path }}/profiles/{{ profile_name }}"
  register: profile_already_exists

- name: Verify if pid file
  ansible.builtin.shell: ps -p `cat "{{ was_base_path }}/profiles/{{ profile_name }}/logs/dmgr/dmgr.pid"`
  register: "dmgr_is_running"
  ignore_errors: true
  changed_when: dmgr_is_running.rc != 0

- name: "Check if stat exists {{ bin_directory }}"
  ansible.builtin.stat:
    path: "{{ bin_directory }}"
  register: bin_dir

- name: "Generate Response file"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ bin_directory }}/{{ item | replace('.j2', '.py') }}"
    owner: "{{ was_owner }}"
    group: "{{ was_group }}"
    mode: '0755'
  when: bin_dir.stat.exists
  with_items: "{{ log_files }}"

- name: "Assigning roles to users"
  ansible.builtin.command: >
    sh wsadmin.sh -lang jython -username {{ was_username }} -password {{ was_password }} -f {{ bin_directory }}/was_users_roles_assigning.py {{ item.username }} "{{ item.roles | join('","') }}"
  register: users_roles_reg
  loop: "{{ users_list_json }}"
  args:
    chdir: "{{ bin_directory }}"
  changed_when: users_roles_reg.rc == 0

- name: Print the result of roles of users
  ansible.builtin.debug:
    msg: "{{ item.stdout }}"
  changed_when: "'Configuration saved successfully.' in item.stdout"
  loop: "{{ users_roles_reg.results }}"

- name: "Purge Response file"
  ansible.builtin.file:
    path: "{{ bin_directory }}/{{ item | replace('.j2', '.py') }}"
    state: absent
  with_items: "{{ log_files }}"
